config/routes.rb
Rails.application.routes.draw do
  resources :elements
  
  devise_for :writers
  # get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"

  scope module: 'writers' do
    resources :songs do
      resources :elements
    end
  end

  # public posts routes using model
  get '/posts' => 'posts#index'
  get '/posts/new' => 'posts#new'

  post '/posts' => 'posts#create', as: 'post_create'

  get '/posts/edit/:id' => 'posts#edit', as: 'post_edit'
  put '/posts/:id' => 'posts#update', as: 'post_update'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/element.rb
class Element < ApplicationRecord
  belongs_to :song

  validates :element_type, inclusion: { in: ['paragraph', 'image', 'video-embed']}

  has_rich_text :content
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true
    validates :lyric, presence: true, length: {minimum: 10}
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :writer

  has_many :elements, dependent: :destroy

  validates :title, presence: true
end

app/models/writer.rb
class Writer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :songs, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    protect_from_forgery with: :null_session

    def index
        @posts = Post.all
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)

        if @post.save
            redirect_to posts_path
        else
            render :new
        end
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])

        if @post.update(post_params)
            redirect_to posts_path
        else  
            render :edit
        end
    end

    private
    def post_params
        params.require(:post).permit(:title, :description, :lyric)
    end
end

app/controllers/writers/elements_controller.rb
module Writers
  class ElementsController < WritersController
    before_action :set_song
    before_action :set_element, only: [:update, :destroy]

    # POST /elements
    def create
      @element = @song.elements.build(element_params)

      if @element.save
        notice = nil
      else
        notice = @element.errors.full_messages.join(". ") << "."
      end
      redirect_to edit_song_path(@song), notice: notice
    end

    # PATCH/PUT /elements/1
    def update
      @element.update(element_params)
      redirect_to edit_song_path(@element.song)
    end

    # DELETE /elements/1
    def destroy
      @element.destroy
      redirect_to elements_url, notice: 'Element was successfully destroyed.'
    end

    private

      def set_song
        @song = current_writer.songs.find(params[:song_id])
      end
      # Use callbacks to share common setup or constraints between actions.
      def set_element
        @element = @song.elements.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def element_params
        params.require(:element).permit(:element_type, :content)
      end
  end
end

app/controllers/writers/songs_controller.rb
module Writers
  class SongsController < WritersController
    before_action :set_song, only: [:show, :edit, :update, :destroy]

    # GET /songs
    def index
      @songs = current_writer.songs
    end

    def show
    end

    # GET /songs/new
    def new
      @song = current_writer.songs.build
    end

    # GET /songs/1/edit
    def edit
      @paragraph = @song.elements.build(element_type: 'paragraph')
    end

    # POST /songs
    def create
      @song = current_writer.songs.build(song_params)

      if @song.save
        redirect_to @song, notice: 'Song was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /songs/1
    def update
      if @song.update(song_params)
        redirect_to @song, notice: 'Song was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /songs/1
    def destroy
     @song.destroy
     redirect_to songs_url, notice: 'Song was successfully Deleted'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_song
        @song = current_writer.songs.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def song_params
        params.require(:song).permit(:title, :description)
      end
  end
end

app/controllers/writers_controller.rb
class WritersController < ApplicationController
    before_action :authenticate_writer!

    layout 'writers'
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/home/index.html.erb
<%# Header %>

    <header class="header-home sticky top-0 flex justify-center items-center gap-10 py-8 custom:flex-col">

        <span class="header-span text-4xl">Wasak Beats Blog</span>
        
        <nav>
            <ul class="nav_links flex gap-5 text-xl custom:text-xl gap-4">
                <li class="hover:border-b-2 hover:border-b-fuchsia-600 text-fuchsia-400"><a href="/">Home</a></li>
                <li class="hover:border-b-2 hover:border-b-fuchsia-600"><%= link_to "Blog", posts_path %></li>
                <li class="hover:border-b-2 hover:border-b-fuchsia-600"><%= link_to "Create Lyrics", songs_path %></li>
                <button><%= link_to "Sign In", songs_path, class: 'signin-btn bg-violet-800 font-semibold hover:bg-violet-900' %></button>
            </ul>
        </nav>

    </header>
    
<%# End of Header %>

<%# Section %>

    <section class="home-section flex justify-center custom:flex-col-reverse fade-in">
        <div class="home-left font-semibold custom:text-center">
            <h2 class="text-4xl custom:text-2xl">Bring your feelings into a song</h2>
            <h2 class="text-4xl mt-2 custom:text-2xl">Create, share your lyrics to<br/> the world now!</h2>
            <br/>
            <%= link_to "Look for Inspirations", posts_path, class: 'signin-btn look-btn bg-violet-800 font-semibold hover:bg-violet-900' %>
        </div>

        <div class="home-right">
            <%= image_tag 'home_bg.png', alt: 'Home image main background' %>
        </div>
    </section>

<%# End of Section %>

    <br/><br/>

    <div class="text-center">
        <span class="text-stone-400 font-semibold uppercase tracking-wide">Learn More</span>
        <br/>
        <span class="text-stone-400 font-semibold">▽</span>
    </div>

    <br/><br/>

<%# Section %>

    <section class="home-section flex gap-20 justify-center custom:flex-col-reverse fade-in">
        <div class="home-left home-left-2 font-semibold custom:text-center">
            <h2 class="text-2xl custom:text-xl">Create, Share, and Sing on the go!</h2>
            <h2 class="text-xl text-stone-400 mt-2 custom:text-lg">Available on the Google playstore<br/> and the Apple app store soon!</h2>
        </div>

        <div class="home-right">
            <%= image_tag 'phone.png', alt: 'Home image main background' %>
        </div>
    </section>

<%# End of Section %>

    <br/><br/>

<%# Section %>

    <section class="home-section flex gap-20 justify-center custom:flex-col gap-0 fade-in">
        <div class="home-left-image font-semibold custom:text-center">
            <%= image_tag 'explore.png', alt: 'Home image main background' %>
        </div>

        <div class="home-right-none-image custom:text-center">
            <h2 class="text-2xl custom:text-xl font-semibold">Explore, Collab, with everybody!</h2>
            <h2 class="text-xl text-stone-400 mt-2 custom:text-lg font-semibold">Explore song lyrics made by others<br/> and try collaborating with them!</h2> 
        </div>
    </section>

<%# End of Section %>

    <br/><br/>

<%# Section %>

    <section class="home-section flex gap-20 justify-center custom:flex-col-reverse fade-in">
        <div class="home-left home-left-2 font-semibold custom:text-center">
            <h2 class="text-2xl custom:text-xl">Create your own Set Privately</h2>
            <h2 class="text-xl text-stone-400 mt-2 custom:text-lg">Create your own library of song lyrics<br/> and get back to it later on!</h2>
        </div>

        <div class="home-right">
            <%= image_tag 'private.png', alt: 'Home image main background' %>
        </div>
    </section>

<%# End of Section %>

<%# Footer %>

    <footer class="bg-stone-800 text-center font-semibold text-2xl mt-4">
        <br/><br/>
        <span class="bg-stone-800">Wasak Beats 2022</span>
        <br/>
        <span class="bg-stone-800 text-xl mt-2">by: Isaac Sarte</span>
        <br/><br/>
    </footer>

<%# End of Footer %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wasak Beats Blog</title>
    <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>
    <meta name="viewport" content="width=device-width,initial-scale=1">
      <%= favicon_link_tag 'wb.jpg' %>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_link_tag 'wind', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/writers.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wasak Beats Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_footer.html.erb
<%# Footer %>

    <footer class="bg-stone-800 text-center font-semibold text-2xl mt-4 fixed bottom-0 w-full lg:relative xl:relative 2xl:fixed mt-16 custom:relative">
        <br/><br/>
        <span class="bg-stone-800">Wasak Beats 2022</span>
        <br/>
        <span class="bg-stone-800 text-xl mt-2">by: Isaac Sarte</span>
        <br/><br/>
    </footer>

<%# End of Footer %>

app/views/posts/_header.html.erb
<%# Header %>

    <header class="header-home sticky top-0 flex justify-center items-center gap-10 py-8 custom:flex-col">

        <span class="header-span text-4xl">Wasak Beats Blog</span>
        
        <nav>
            <ul class="nav_links flex gap-5 text-xl custom:text-xl gap-4">
                <li class="hover:border-b-2 hover:border-b-fuchsia-600"><a href="/">Home</a></li>
                <li class="hover:border-b-2 hover:border-b-fuchsia-600 text-fuchsia-400"><%= link_to "Blog", posts_path %></li>
                <li class="hover:border-b-2 hover:border-b-fuchsia-600"><%= link_to "Create Lyrics", songs_path %></li>
                <button><%= link_to "Sign In", songs_path, class: 'signin-btn bg-violet-800 font-semibold hover:bg-violet-900' %></button>
            </ul>
        </nav>

    </header>
    
<%# End of Header %>

app/views/posts/edit.html.erb
<%# Header %>

<%= render 'header' %>

<%# End of Header %>

<br/><br/>

<section class="post-new max-w-6xl mt-16 xl:mt-4 custom:-mt-4">

    <div>
        <div class="md:grid md:grid-cols-3 md:gap-6">
            <div class="md:col-span-1">
                <div class="px-4 sm:px-0">
                    <i class='bx bx-arrow-back'></i> <%= link_to 'Back to Blog', posts_path %>
                    <h3 class="text-2xl mt-2 font-semibold leading-6 text-white">Updating Song Information</h3>
                    <p class="mt-4 text-sm text-slate-300">This information will be displayed publicly so be careful what you share.</p>
                </div>
            </div>

            <div class="mt-6 md:mt-1 md:col-span-2 custom:mt-1">

                <%= form_with scope: :post, url: post_update_path(@post.id), method: 'put', data: {turbo_confirm: 'Are you sure want to edit and collab with this song?'}, class: 'song-form-new custom:w-3/4' do |form| %>
                  <div class="shadow sm:rounded-md sm:overflow-hidden">
                        <div class="px-4 py-5 bg-gray-50 rounded-md space-y-6 sm:p-6">
                            <div class="grid grid-cols-3 gap-6">
                                <div class="col-span-3 sm:col-span-2 bg-gray-50">
                                    <label for="song-title" class="block text-lg font-semibold bg-gray-50 text-black"> Song Title: </label>
                                    <div class="mt-1 flex rounded-md shadow-sm bg-gray-50">
                                        <%= form.text_field :title, class: "song-input-new text-black focus:border-indigo-600 flex-1 block w-full sm:text-sm", placeholder: "Enter song title" %>
                                    </div>
                                </div>
                            </div>

                            <div class="bg-gray-50">
                                <label for="about" class="block text-lg font-semibold bg-gray-50 text-black"> Description: </label>
                                    <div class="mt-1 bg-gray-50">
                                        <%= form.text_area :description, rows: "3", class: "song-desc-input-new text-black shadow-sm mt-1 block w-full sm:text-sm", placeholder: "Enter song description" %>
                                    </div>
                                <p class="mt-2 text-sm bg-gray-50 text-gray-800 font-semibold">Brief description for your song.</p>
                            </div>

                            <div class="bg-gray-50">
                                <label for="about" class="block text-lg font-semibold bg-gray-50 text-black"> Lyrics: </label>
                                <div class="mt-1 bg-gray-50">
                                    <%= form.text_area :lyric, rows: "3", class: "song-desc-input-new text-black shadow-sm mt-1 block w-full sm:text-sm", placeholder: "Type song lyrics here" %>
                                </div>
                            </div>

                            <% if @post.errors.any? %>
                                <div class="error-new-public">
                                    <ul>
                                        <% @post.errors.each do |error| %>
                                            <li><%= error.full_message %></li>
                                        <% end %>
                                    </ul>
                                </div>
                            <% end %>

                            <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
                                <%= form.submit "Collab with this Song", class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
                            </div>
                        </div>
                    </div>
                <% end %>

            </div>
        </div>
    </div>

</section>

<%# Footer %>

    <%= render 'footer' %>

<%# End of Footer %>

app/views/posts/index.html.erb
<%# Header %>

<%= render 'header' %>

<%# End of Header %>

<div class="post-index mt-16 sticky top-0 text-center text-3xl font-extrabold text-white custom:mt-0">
    <i class='bx bx-plus mt-2' ></i><%= link_to 'Share and Collab another New Song', posts_new_path, class:'hover:text-slate-300' %>
</div>

<div class="flex justify-evenly post-index-image-top">
    <div class="">
        <%= image_tag 'circle.png' %>
    </div>

    <div class="">
        <%= image_tag 'curvy.png' %>
    </div>
</div>

<section class="post-index-section mt-8">

    <div class="post-index-section-div max-w-7xl grid grid-cols-4 gap-8 place-items-center justify-items-center custom:z-10 md:grid-cols-2 lg:grid-cols-3 xl:max-w-5xl 2xl:grid-cols-4">
        <% @posts.each do |post| %>

            <div class="bg-violet-900 rounded-lg p-4 flex-col">
                <p class="bg-violet-900 font-semibold text-xl text-center"><i class='bx bxs-music bg-violet-900 text-gray-300'></i> Song Title: </p>
                <h3 class="bg-violet-900 font-semibold text-center mt-2"><%= post.title %></h3>
                <hr />

                <br/>

                <p class="bg-violet-900 font-semibold text-xl">Description: </p>
                <h3 class="bg-violet-900"><%= post.description %></h3>

                <br/>

                <p class="bg-violet-900 font-semibold text-xl">Lyrics: </p>
                <h3 class="bg-violet-900"><%= post.lyric %></h3>

                <br/>

                <%= link_to '✒️Edit and Collab with this Song', post_edit_path(post.id), class: 'bg-violet-900 text-emerald-300 font-semibold' %>
            </div>

        <% end %>
    </div>

</section>

<div class="mt-32 bottom-0 flex justify-evenly post-index-image-bot">
    <div class="">
        <%= image_tag 'triangle.png' %>
    </div>
    <div class="">
        <%= image_tag 'curved.png' %>
    </div>
</div>

app/views/posts/new.html.erb
<%# Header %>

<%= render 'header' %>

<%# End of Header %>

<br/><br/>

<section class="post-new max-w-6xl mt-16 xl:mt-4 custom:-mt-4">

    <div>
        <div class="md:grid md:grid-cols-3 md:gap-6">
            <div class="md:col-span-1">
                <div class="px-4 sm:px-0">
                    <i class='bx bx-arrow-back'></i> <%= link_to 'Back to Blog', posts_path %>
                    <h3 class="text-2xl mt-2 font-semibold leading-6 text-white">Song Information</h3>
                    <p class="mt-4 text-sm text-slate-300">This information will be displayed publicly so be careful what you share.</p>
                </div>
            </div>

            <div class="mt-6 md:mt-1 md:col-span-2 custom:mt-1">

                <%= form_with scope: :post, url: post_create_path, local: true, data: {turbo: false}, class: 'song-form-new custom:w-3/4' do |form| %>
                    <div class="shadow sm:rounded-md sm:overflow-hidden">
                        <div class="px-4 py-5 bg-gray-50 rounded-md space-y-6 sm:p-6">
                            <div class="grid grid-cols-3 gap-6">
                                <div class="col-span-3 sm:col-span-2 bg-gray-50">
                                    <label for="song-title" class="block text-lg font-semibold bg-gray-50 text-black"> Song Title: </label>
                                    <div class="mt-1 flex rounded-md shadow-sm bg-gray-50">
                                        <%= form.text_field :title, class: "song-input-new text-black focus:border-indigo-600 flex-1 block w-full sm:text-sm", placeholder: "Enter song title" %>
                                    </div>
                                </div>
                            </div>

                            <div class="bg-gray-50">
                                <label for="about" class="block text-lg font-semibold bg-gray-50 text-black"> Description: </label>
                                    <div class="mt-1 bg-gray-50">
                                        <%= form.text_area :description, rows: "3", class: "song-desc-input-new text-black shadow-sm mt-1 block w-full sm:text-sm", placeholder: "Enter song description" %>
                                    </div>
                                <p class="mt-2 text-sm bg-gray-50 text-gray-800 font-semibold">Brief description for your song.</p>
                            </div>

                            <div class="bg-gray-50">
                                <label for="about" class="block text-lg font-semibold bg-gray-50 text-black"> Lyrics: </label>
                                    <div class="mt-1 bg-gray-50">
                                        <%= form.text_area :lyric, rows: "3", class: "song-desc-input-new text-black shadow-sm mt-1 block w-full sm:text-sm", placeholder: "Type song lyrics here" %>
                                    </div>
                            </div>

                            <% if @post.errors.any? %>
                                <div class="error-new-public">
                                    <ul>
                                        <% @post.errors.each do |error| %>
                                            <li><%= error.full_message %></li>
                                        <% end %>
                                    </ul>
                                </div>
                            <% end %>

                            <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
                                <%= form.submit "Create Song", class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
                            </div>
                        </div>
                    </div>
                <% end %>

            </div>
        </div>
    </div>

</section>

<%# Footer %>

    <%= render 'footer' %>

<%# End of Footer %>

app/views/writers/songs/_footer.html.erb
<%# Footer %>

    <footer class="bg-stone-800 text-center font-semibold text-2xl mt-4 fixed bottom-0 w-full 2xl:fixed custom:fixed">
        <br/><br/>
        <span class="bg-stone-800">Wasak Beats 2022</span>
        <br/>
        <span class="bg-stone-800 text-xl mt-2">by: Isaac Sarte</span>
        <br/><br/>
    </footer>

<%# End of Footer %>

app/views/writers/songs/_form.html.erb
<section class="post-new max-w-6xl mt-16 xl:mt-4 custom:-mt-4">

  <div>
    <div class="md:grid md:grid-cols-3 md:gap-6">
      <div class="md:col-span-1">
          <div class="px-4 sm:px-0">
              ← <%= link_to 'Back to Your Songs', songs_path %>
              <h3 class="text-2xl mt-2 font-semibold leading-6 text-white">Song Information</h3>
          </div>
      </div>

      <div class="mt-6 md:mt-1 md:col-span-2 custom:mt-1">

        <%= form_with(model: @song, local: true, data: {turbo: false}, class: 'song-form-new custom:w-3/4') do |form| %>

            <%# =================== %>

            <div class="shadow sm:rounded-md sm:overflow-hidden">
              <div class="px-4 py-5 bg-gray-50 rounded-md space-y-6 sm:p-6">
                <div class="grid grid-cols-3 gap-6">
                  <div class="col-span-3 sm:col-span-2 bg-gray-50">
                    <label for="song-title" class="block text-lg font-semibold bg-gray-50 text-black"> Song Title: </label>
                    <div class="mt-1 flex rounded-md shadow-sm bg-gray-50">
                      <%= form.text_field :title, class: "song-input-new text-black focus:border-indigo-600 flex-1 block w-full sm:text-sm", placeholder: "Enter song title" %>
                    </div>
                  </div>
                </div>

                <div class="bg-gray-50">
                  <label for="about" class="block text-lg font-semibold bg-gray-50 text-black"> Description: </label>
                  <div class="mt-1 bg-gray-50">
                    <%= form.text_area :description, rows: "3", class: "song-desc-input-new text-black shadow-sm mt-1 block w-full sm:text-sm", placeholder: "Enter song description" %>
                  </div>
                  <p class="mt-2 text-sm bg-gray-50 text-gray-800 font-semibold">Brief description for your song.</p>
                </div>

                <% if @song.errors.any? %>
                  <div class="error-new-private">
            
                    <ul>
                      <% @song.errors.each do |error| %>
                        <li><%= error.full_message %></li>
                      <% end %>
                    </ul>
                    
                  </div>
                <% end %>

                <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
                    <%= form.submit "Create Song", class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
                </div>
              </div>
            </div>


        <% end %>

      </div>
    </div>
  </div>

</section>

app/views/writers/songs/_header.html.erb
<%# Header %>

    <header class="header-home sticky top-0 flex justify-center items-center gap-10 py-8 custom:flex-col">

        <span class="header-span text-4xl">Wasak Beats Blog</span>
        
        <nav>
            <ul class="nav_links flex gap-5 text-xl custom:text-xl gap-4">
                <li class="hover:border-b-2 hover:border-b-fuchsia-600"><a href="/">Home</a></li>
                <li class="hover:border-b-2 hover:border-b-fuchsia-600"><%= link_to "Blog", posts_path %></li>
                <li class="hover:border-b-2 hover:border-b-fuchsia-600"><%= link_to "Sign out", destroy_writer_session_path %></li>
                <button><%= link_to "New Song", new_song_path, class: 'signin-btn bg-violet-800 font-semibold hover:bg-violet-900' %></button>
            </ul>
        </nav>

    </header>
    
<%# End of Header %>

app/views/writers/songs/_song.html.erb
<div class="show-song bg-gray-50 shadow overflow-hidden rounded-md sm:rounded-lg max-w-5xl mt-8 custom:w-3/4">
  <div class="px-4 py-5 sm:px-6 bg-gray-50">
    <h3 class="text-xl leading-6 font-semibold bg-gray-50 text-black uppercase">Song Details:</h3>
  </div>
  <div class="border-t border-gray-200">
    <dl class="bg-gray-50">
      <div class="px-4 py-5 bg-gray-50 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-xl font-semibold bg-gray-50 text-black">Song Title: </dt>
        <dd class="mt-1 text-lg bg-gray-50 text-gray-900 sm:mt-0 sm:col-span-2"><%= song.title %></dd>
      </div>
      <div class="px-4 py-5 bg-gray-50 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-xl font-semibold bg-gray-50 text-black">Description: </dt>
        <dd class="mt-1 text-lg bg-gray-50 text-gray-900 sm:mt-0 sm:col-span-2"><%= song.description %></dd>
      </div>
      <div class="bg-gray-50 gap-4 mt-4 mb-4">
        <%= link_to "✒️Edit this song", edit_song_path(@song), class: 'bg-gray-50 text-emerald-700 font-semibold' %>
        <%= link_to " ↩ Back to songs", songs_path, class: 'bg-gray-50 text-violet-800 font-semibold ml-2' %>
      </div>
    </dl>
  </div>
</div>

app/views/writers/songs/new.html.erb
<%# Header %>

<%= render 'header' %>

<%# End of Header %>

<br/><br/>

<%= render "form", post: @song %>

<%# Footer %>

    <footer class="bg-stone-800 text-center font-semibold text-2xl mt-4 fixed bottom-0 w-full 2xl:fixed custom:relative">
        <br/><br/>
        <span class="bg-stone-800">Wasak Beats 2022</span>
        <br/>
        <span class="bg-stone-800 text-xl mt-2">by: Isaac Sarte</span>
        <br/><br/>
    </footer>

<%# End of Footer %>

app/views/writers/songs/show.html.erb
<%# Header %>

<%= render 'header' %>

<%# End of Header %>

<br/><br/>

<%= render @song %>

<%# Footer %>

    <footer class="bg-stone-800 text-center font-semibold text-2xl mt-4 fixed bottom-0 w-full 2xl:fixed custom:relative">
        <br/><br/>
        <span class="bg-stone-800">Wasak Beats 2022</span>
        <br/>
        <span class="bg-stone-800 text-xl mt-2">by: Isaac Sarte</span>
        <br/><br/>
    </footer>

<%# End of Footer %>